In [1]:
%reload_ext autoreload
%autoreload 2

from metricstudio import DataLoader

loader = DataLoader()

In [2]:
stock = loader.load_adjusted_stock_duckdb(
    columns=['name', 'close', 'market_cap'],
    start='2025-01-01',
    end='2025-12-31',
    market=['KOSPI'],
)

In [3]:
stock

                         name         close     market_cap
date       ticker
2025-01-02 000020        동화약품   6300.000000   175968261000
           000040       KR모터스    459.000000    27600986412
           000050          경방   6410.000000   175731880700
           000070       삼양홀딩스  43374.760994   556677615000
           000075      삼양홀딩스우  51700.000000    15719798600
...                       ...           ...            ...
2025-12-30 487570        HS효성  57900.000000   215731173300
           489790        한화비전  44900.000000  2266928711000
           499790       GS피앤엘  42000.000000   832895322000
           900140    엘브이엠씨홀딩스   1600.000000   309184691200
           950210  프레스티지바이오파마  12850.000000   772235591750

[220772 rows x 3 columns]

In [4]:
idx = loader.load_index_duckdb(
    columns=['open','high','low','close','market_cap'],
    start='2020-01-01',
    # end='2025-01-31',
    names=['코스피'],
)

In [5]:
idx

                    open     high      low    close        market_cap
date       name
2020-01-02 코스피   2201.21  2202.32  2171.84  2175.17  1461424793589993
2020-01-03 코스피   2192.58  2203.38  2165.39  2176.46  1462298971774498
2020-01-06 코스피   2154.97  2164.42  2149.95  2155.07  1448385085188395
2020-01-07 코스피   2166.60  2181.62  2164.27  2175.54  1462298814406954
2020-01-08 코스피   2156.27  2162.32  2137.72  2151.31  1446631314388659
...                  ...      ...      ...      ...               ...
2026-03-06 코스피   5491.02  5609.98  5381.27  5584.87  4605057307856441
2026-03-09 코스피   5265.37  5327.42  5096.16  5251.87  4331264221607092
2026-03-10 코스피   5523.21  5595.88  5427.88  5532.59  4567316826262150
2026-03-11 코스피   5658.72  5746.36  5559.69  5609.95  4633384475718061
2026-03-12 코스피   5567.65  5629.07  5527.47  5583.25  4608099993232712

[1519 rows x 5 columns]